/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.faktura;

import controller.Controller;
import domain.Faktura;
import domain.JedinicaMere;
import domain.OdgovornoLice;
import domain.Proizvod;
import domain.StopaPDV;
import domain.Zaposleni;
import forms.proizvod.ProizvodUpdate;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class FakturaUpdate extends javax.swing.JFrame {

    /**
     * Creates new form FakturaUpdate
     */
    Faktura f = new Faktura();
    public FakturaUpdate() {
        initComponents();
        CBFakture();
     CBStope();
      CBOdgLica();
      CBZaposleni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOdaberi = new javax.swing.JButton();
        cmbFakture = new javax.swing.JComboBox();
        btnIzmeni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDatumFakturisanja = new javax.swing.JTextField();
        txtDatumprometa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbOdgLica = new javax.swing.JComboBox();
        cmbZaposleni = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        cmbStope = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOdaberi.setText("Odaberi");
        btnOdaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdaberiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel1.setText("Stopa PDV:");

        jLabel2.setText("Datum fakturisanja");

        jLabel3.setText("(dd.MM.yyyy)");

        jLabel4.setText("Datum prometa: ");

        jLabel5.setText("Odgovorno lice dobavljaca:");

        jLabel6.setText("(dd.MM.yyyy)");

        jLabel7.setText("Zaposleni:");

        jLabel8.setText("Ukupno: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzmeni))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbFakture, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDatumprometa, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDatumFakturisanja)
                                    .addComponent(cmbOdgLica, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUkupno)
                                    .addComponent(cmbStope, 0, 432, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOdaberi)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbFakture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOdaberi))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatumFakturisanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatumprometa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(cmbStope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbOdgLica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(cmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnIzmeni)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdaberiActionPerformed
         // TODO add your handling code here:
    enableFormFields();
       
        
        f = (Faktura) cmbFakture.getSelectedItem();
        DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        txtDatumFakturisanja.setText( df.format(f.getDatumfakturisanja()));
        txtDatumprometa.setText(df.format(f.getDatumprometa()));
        System.out.println(f.getStopa());
        cmbStope.setSelectedItem(f.getStopa());
        System.out.println(f.getZ());
       cmbZaposleni.setSelectedItem(f.getZ());
   cmbOdgLica.setSelectedItem(f.getOdgLice());
   txtUkupno.setText(f.getUkupno() + "");
          
    }//GEN-LAST:event_btnOdaberiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
         try {
             // TODO add your handling code here:
             
             
             int sifrafak = f.getSifrafakture();
            DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
            Date datumprometa = df.parse(txtDatumprometa.getText().trim());
            Date datumfakturisanja = df.parse(txtDatumFakturisanja.getText().trim());
            Zaposleni z = (Zaposleni) cmbZaposleni.getSelectedItem();
            StopaPDV stopa = (StopaPDV) cmbStope.getSelectedItem();
            OdgovornoLice odgLice = (OdgovornoLice) cmbOdgLica.getSelectedItem();
             double ukupno = Double.parseDouble(txtUkupno.getText().trim());
             
             Faktura f = new Faktura(sifrafak, datumfakturisanja, datumprometa, stopa, z, odgLice, ukupno);
             
             Controller.getInstance().azurirajFakturu(f);
             JOptionPane.showMessageDialog(this, "Uspesna izmena fakture");
             this.dispose();

         } catch (Exception ex) {
             ex.printStackTrace();
             JOptionPane.showMessageDialog(this, "Greska prilikom izmene fakture");
         }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FakturaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FakturaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FakturaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FakturaUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FakturaUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdaberi;
    private javax.swing.JComboBox cmbFakture;
    private javax.swing.JComboBox cmbOdgLica;
    private javax.swing.JComboBox cmbStope;
    private javax.swing.JComboBox cmbZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDatumFakturisanja;
    private javax.swing.JTextField txtDatumprometa;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    private void CBFakture() {
     disableFormFields();
        
        try {
            cmbFakture.removeAllItems();
            List<Faktura> fakture = Controller.getInstance().vratiFakture();
            for (Faktura fak : fakture) {
                cmbFakture.addItem(fak);
            }
        } catch (Exception ex) {
            Logger.getLogger(ProizvodUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CBStope()  {
    try{
            cmbStope.removeAllItems();
            List<StopaPDV> stope = Controller.getInstance().vratiStopePDV();
            
            for (StopaPDV s : stope) {
                  System.out.println(s + "ddddddddddddddddd");
                cmbStope.addItem(s );
              
                
    
    }
     } catch (Exception ex) {
             Logger.getLogger(FakturaUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }

    private void CBOdgLica() {
        try{
            cmbOdgLica.removeAllItems();
            List<OdgovornoLice> odgLica = Controller.getInstance().vratiOdgLicaSvihDobavljaca();
            
            for (OdgovornoLice ol : odgLica) {
                cmbOdgLica.addItem(ol);
    
    }
     } catch (Exception ex) {
            System.out.println("Greska prilikom vracanja liste stp. pdv");
            System.out.println(ex);
        }
    }

    private void CBZaposleni() {
        try{
            cmbZaposleni.removeAllItems();
            List<Zaposleni> zaposleni = Controller.getInstance().vratiZaposleneView();
            
            for (Zaposleni z : zaposleni) {
                cmbZaposleni.addItem(z);
    
    }
     } catch (Exception ex) {
            System.out.println("Greska prilikom vracanja liste zaposlenih");
            System.out.println(ex);
        }
    }
    
    private void disableFormFields() {
        
        txtDatumFakturisanja.setEnabled(false);
        txtDatumprometa.setEnabled(false);
        cmbStope.setEnabled(false);
          cmbOdgLica.setEnabled(false);
            cmbZaposleni.setEnabled(false);
            btnIzmeni.setEnabled(false);
    
        
    }
    
    private void enableFormFields() {
          txtDatumFakturisanja.setEnabled(true);
        txtDatumprometa.setEnabled(true);
        cmbStope.setEnabled(true);
          cmbOdgLica.setEnabled(true);
            cmbZaposleni.setEnabled(true);
             btnIzmeni.setEnabled(true);
    }
}
