/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.faktura;

import controller.Controller;
import domain.Cena;
import domain.Faktura;
import forms.cena.CenaView;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Korisnik
 */
public class FakturaView extends javax.swing.JFrame {

    /**
     * Creates new form FakturaView
     */
    public FakturaView() {
        initComponents();
        initFrom();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFaktura = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableFaktura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sifra fakture", "Datum prometa", "Datum fakturisanja", "Sifra stope pdv", "Sifra zaposlenog", "Sifra dobavljaca", "Sifra odgovornog lica", "Ukupno"
            }
        ));
        jScrollPane1.setViewportView(tableFaktura);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FakturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FakturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FakturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FakturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FakturaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFaktura;
    // End of variables declaration//GEN-END:variables

    private void initFrom() {
       try {
            List<Faktura> fakture = Controller.getInstance().vratiFaktureView();
            initTable(fakture);
        } catch (Exception ex) {
            Logger.getLogger(CenaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initTable(List<Faktura> fakture) {
         DefaultTableModel dtm = (DefaultTableModel) tableFaktura.getModel();
        removeAllRows(dtm);
               for (Faktura f : fakture) {
                Object [] row = new Object[8];
                row[0] = f.getSifrafakture();
                row[1] = f.getDatumprometa();
                row[2] = f.getDatumfakturisanja();
                row[3] = f.getSifrastopepdv();
                row[4] = f.getSifrazaposlenog();
                 row[5] = f.getSifradobavljaca();
                 row[6] = f.getSifraodglica();
                 row[7] = f.getUkupno();
                
                
                dtm.addRow(row);
            }
    }
    private void removeAllRows(DefaultTableModel dtm) {
        dtm.setRowCount(0);
    }
}
