/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.proizvod;

import controller.Controller;
import domain.Proizvod;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Korisnik
 */
public class ProizvodView extends javax.swing.JFrame {

    /**
     * Creates new form ProizvodView
     */
    public ProizvodView() {
        initComponents();
         initForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivProizvoda = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProizvodi = new javax.swing.JTable();
        jbtnVratiNaziv = new javax.swing.JRadioButton();
        jbtnVratiSve = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretrazi po nazivu proizvoda: ");

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tableProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sifra proizvoda", "Naziv proizvoda", "       JM", "Trenutna cena"
            }
        ));
        jScrollPane1.setViewportView(tableProizvodi);

        jbtnVratiNaziv.setText("Pretrazi po nazivu");
        jbtnVratiNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVratiNazivActionPerformed(evt);
            }
        });

        jbtnVratiSve.setText("Vrati sve");
        jbtnVratiSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVratiSveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi))
                    .addComponent(jbtnVratiNaziv))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtnVratiSve)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtnVratiNaziv)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(12, 12, 12)
                .addComponent(jbtnVratiSve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            String naziv = txtNazivProizvoda.getText().trim();
            List<Proizvod> artikli = Controller.getInstance().pronadjiProizvodPoNazivu(naziv);
            initTable(artikli);
        } catch (Exception ex) {
            Logger.getLogger(ProizvodView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void jbtnVratiNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVratiNazivActionPerformed
          jbtnVratiSve.setSelected(false);
        btnPretrazi.setEnabled(true);
        txtNazivProizvoda.setEnabled(true);
    }//GEN-LAST:event_jbtnVratiNazivActionPerformed

    private void jbtnVratiSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVratiSveActionPerformed
        initForm();
    }//GEN-LAST:event_jbtnVratiSveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProizvodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProizvodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProizvodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProizvodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProizvodView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jbtnVratiNaziv;
    private javax.swing.JRadioButton jbtnVratiSve;
    private javax.swing.JTable tableProizvodi;
    private javax.swing.JTextField txtNazivProizvoda;
    // End of variables declaration//GEN-END:variables

    private void initForm() {
        try {
             jbtnVratiNaziv.setSelected(false);
        jbtnVratiSve.setSelected(true);
        txtNazivProizvoda.setEnabled(false);
        btnPretrazi.setEnabled(false);
            List<Proizvod> proizvodi = Controller.getInstance().vratiProizvode();
            initTable(proizvodi);
        } catch (Exception ex) {
            Logger.getLogger(ProizvodView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initTable(List<Proizvod> proizvodi) {
         DefaultTableModel dtm = (DefaultTableModel) tableProizvodi.getModel();
        removeAllRows(dtm);
            for (Proizvod proizvod : proizvodi) {
                Object [] row = new Object[4];
                row[0] = proizvod.getSifraproizvoda();
                row[1] = proizvod.getNazivproizvoda();
                row[2] = proizvod.getJm();
                row[3] = proizvod.getTrenutnacena();
                
                
                dtm.addRow(row);
            }
    }

    private void removeAllRows(DefaultTableModel dtm) {
           dtm.setRowCount(0);
    }
}
