/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.stavkanarudzbenice;

import controller.Controller;
import domain.JedinicaMere;
import domain.Narudzbenica;
import domain.Proizvod;
import domain.StavkaFakture;
import domain.StavkaNarudzbenice;
import forms.proizvod.ProizvodUpdate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class StavkaNarudzbeniceInsert extends javax.swing.JFrame {

    /**
     * Creates new form StavkaNarudzbeniceInsert
     */
    public StavkaNarudzbeniceInsert() {
        initComponents();
        CBNarudzbenice();
        CBProizvodi();
        CBJM();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbNarudzbenice = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbProizvodi = new javax.swing.JComboBox();
        btnUbaci = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbJM = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Narudzbenica: ");

        jLabel2.setText("Proizvod: ");

        btnUbaci.setText("Ubaci");
        btnUbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbaciActionPerformed(evt);
            }
        });

        jLabel4.setText("Jedinica mere:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbNarudzbenice, 0, 278, Short.MAX_VALUE)
                            .addComponent(cmbProizvodi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUbaci))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbJM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbNarudzbenice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnUbaci)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbaciActionPerformed
        try {
            // TODO add your handling code here:
            
            Narudzbenica n = (Narudzbenica) cmbNarudzbenice.getSelectedItem();
            Proizvod p = (Proizvod) cmbProizvodi.getSelectedItem();
            JedinicaMere jm = (JedinicaMere) cmbJM.getSelectedItem();
            
            StavkaNarudzbenice sn = new StavkaNarudzbenice(n, p, jm);
            Controller.getInstance().sacuvajStavkuNarudzbenice(sn);
            JOptionPane.showMessageDialog(this,  "Stavka je uspesno sacuvana!");
            this.dispose();
           
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this,  "Greska prilikom cuvanja stavke!");

        }
    }//GEN-LAST:event_btnUbaciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StavkaNarudzbeniceInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUbaci;
    private javax.swing.JComboBox cmbJM;
    private javax.swing.JComboBox cmbNarudzbenice;
    private javax.swing.JComboBox cmbProizvodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
  private void CBJM() {
        
        try {
            cmbJM.removeAllItems();
            List<JedinicaMere> jm = Controller.getInstance().selectJM();
            
            for (JedinicaMere jm1 : jm) {
                cmbJM.addItem(jm1);
            }
            
            
        } catch (Exception ex) {
            System.out.println("Greska prilikom vracanja liste JM");
            System.out.println(ex);
        }}
   

    private void CBProizvodi() {
        
        try {
            cmbProizvodi.removeAllItems();
            List<Proizvod> proizvodi = Controller.getInstance().vratiProizvode();
            for (Proizvod p : proizvodi) {
                cmbProizvodi.addItem(p);
            }
        } catch (Exception ex) {
            Logger.getLogger(StavkaNarudzbeniceInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CBNarudzbenice() {
        try {
            cmbNarudzbenice.removeAllItems();
            List<Narudzbenica> narudzbenice = Controller.getInstance().vratiNarudzbenice();
            for (Narudzbenica n : narudzbenice) {
                cmbNarudzbenice.addItem(n);
            }
        } catch (Exception ex) {
            Logger.getLogger(StavkaNarudzbeniceInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
