/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.stavkanarudzbenice;

import controller.Controller;
import domain.JedinicaMere;
import domain.Proizvod;
import domain.StavkaNarudzbenice;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Korisnik
 */
public class StavkaNarudzbeniceUpdate extends javax.swing.JFrame {

    /**
     * Creates new form StavkaNarudzbeniceUpdate
     */
    StavkaNarudzbenice sn = new StavkaNarudzbenice();
    public StavkaNarudzbeniceUpdate() {
        initComponents();
        CBStavke();
        CBProizvod();
        CBJM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbStavke = new javax.swing.JComboBox();
        btnOdaberi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        cmbProizvod = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbJM = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Odaberi stavku narudzbenice za izmenu:");

        btnOdaberi.setText("Odaberi");
        btnOdaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdaberiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jLabel2.setText("Proizvod:");

        jLabel3.setText("Jedinica mere:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIzmeni)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cmbStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnOdaberi))))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJM, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOdaberi))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdaberiActionPerformed
        enableFormFields();
          sn = (StavkaNarudzbenice) cmbStavke.getSelectedItem();
       
        enableFormFields();
        cmbProizvod.setSelectedItem(sn.getProizvod());
        cmbJM.setSelectedItem(sn.getJm());
    }//GEN-LAST:event_btnOdaberiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
         try {
             // TODO add your handling code here:
             
           StavkaNarudzbenice stavka = new StavkaNarudzbenice(sn.getNarudzbenica(), sn.getRbrstavke(), (Proizvod) cmbProizvod.getSelectedItem(), (JedinicaMere) cmbJM.getSelectedItem());
         
             Controller.getInstance().azurirajStavkuNarudzbenice(stavka);
             JOptionPane.showMessageDialog(this, "Uspesna izmena stavke narudzbenice");
             this.dispose();

         } catch (Exception ex) {
             ex.printStackTrace();
             JOptionPane.showMessageDialog(this, "Greska prilikom izmene stavke narudzbenice");
         }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StavkaNarudzbeniceUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StavkaNarudzbeniceUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdaberi;
    private javax.swing.JComboBox cmbJM;
    private javax.swing.JComboBox cmbProizvod;
    private javax.swing.JComboBox cmbStavke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void CBProizvod() {
         try {
            cmbProizvod.removeAllItems();
            List<Proizvod> proizvodi = Controller.getInstance().vratiProizvode();
            for (Proizvod p : proizvodi) {
                cmbProizvod.addItem(p);
            }
        } catch (Exception ex) {
            Logger.getLogger(StavkaNarudzbeniceUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void CBJM() {
         try {
            cmbJM.removeAllItems();
            List<JedinicaMere> jm = Controller.getInstance().selectJM();
            
            for (JedinicaMere jm1 : jm) {
                cmbJM.addItem(jm1);
            }
            
            
        } catch (Exception ex) {
            System.out.println("Greska prilikom vracanja liste JM");
            System.out.println(ex);
        }
    }

    private void CBStavke() {
       try {
           disableFormFields();
            cmbStavke.removeAllItems();
            List<StavkaNarudzbenice> stavke = Controller.getInstance().vratiStavkeNarudzbenice();
            
            for (StavkaNarudzbenice sn : stavke) {
                cmbStavke.addItem(sn);
            }
            
            
        } catch (Exception ex) {
            System.out.println("Greska prilikom vracanja liste stavki");
            System.out.println(ex.getMessage());
        }
    }
      private void disableFormFields() {
        
       cmbProizvod.setEnabled(false);
      cmbJM.setEnabled(false);
      btnIzmeni.setEnabled(false);
    
        
    }
    
    private void enableFormFields() {
         cmbProizvod.setEnabled(true);
      cmbJM.setEnabled(true);
      btnIzmeni.setEnabled(true);
    }
}
